#include "./operation_tests.h"
#include "./core_vector_operation_tests.h"
#include "./core_standard_operation_tests.h"
#include "../abyparty_test_environment/aby_test_environment.h"

OPERATIONTEST(vectorBoolIO, S_BOOL, IOVectorOperationThread)
OPERATIONTEST(vectorYaoIO, S_YAO, IOVectorOperationThread)
OPERATIONTEST(vectorArithIO, S_ARITH, IOVectorOperationThread)
OPERATIONTEST(vectorSplutIO, S_SPLUT, IOVectorOperationThread)
//OPERATIONTEST(vectorBoolCons, S_BOOL, ConsVectorOperationThread)
//OPERATIONTEST(vectorYaoCons, S_YAO, ConsVectorOperationThread)
//OPERATIONTEST(vectorArithCons, S_ARITH, ConsVectorOperationThread)
//OPERATIONTEST(vectorSplutCons, S_SPLUT, ConsVectorOperationThread)
OPERATIONTEST(vectorBoolAdd, S_BOOL, AddVectorOperationThread)
OPERATIONTEST(vectorYaoAdd, S_YAO, AddVectorOperationThread)
OPERATIONTEST(vectorArithAdd, S_ARITH, AddVectorOperationThread)
OPERATIONTEST(vectorSPLUTAdd, S_SPLUT, AddVectorOperationThread)
OPERATIONTEST(vectorBoolSub, S_BOOL, SubVectorOperationThread)
OPERATIONTEST(vectorYaoSub, S_YAO, SubVectorOperationThread)
OPERATIONTEST(vectorArithSub, S_ARITH, SubVectorOperationThread)
OPERATIONTEST(vectorSplutSub, S_SPLUT, SubVectorOperationThread)
OPERATIONTEST(vectorBoolMul, S_BOOL, MulVectorOperationThread)
OPERATIONTEST(vectorYaoMul, S_YAO, MulVectorOperationThread)
OPERATIONTEST(vectorArithMul, S_ARITH, MulVectorOperationThread)
OPERATIONTEST(vectorSplutMul, S_SPLUT, MulVectorOperationThread)
OPERATIONTEST(vectorBoolXor, S_BOOL, XorVectorOperationThread)
OPERATIONTEST(vectorYaoXor, S_YAO, XorVectorOperationThread)
OPERATIONTEST(vectorSplutXor, S_SPLUT, XorVectorOperationThread)
OPERATIONTEST(vectorBoolAnd, S_BOOL, XorVectorOperationThread)
OPERATIONTEST(vectorYaoAnd, S_YAO, AndVectorOperationThread)
OPERATIONTEST(vectorSplutAnd, S_SPLUT, AndVectorOperationThread)
OPERATIONTEST(vectorBoolCmp, S_BOOL, CmpVectorOperationThread)
OPERATIONTEST(vectorYaoCmp, S_YAO, CmpVectorOperationThread)
OPERATIONTEST(vectorSplutCmp, S_SPLUT, CmpVectorOperationThread)
OPERATIONTEST(vectorBoolEq, S_BOOL, EqVectorOperationThread)
OPERATIONTEST(vectorYaoEq, S_YAO, EqVectorOperationThread)
OPERATIONTEST(vectorSplutEq, S_SPLUT, EqVectorOperationThread)
OPERATIONTEST(vectorBooLMux, S_BOOL, MuxVectorOperationThread)
OPERATIONTEST(vectorYaoMux, S_YAO, MuxVectorOperationThread)
OPERATIONTEST(vectorSplutMux, S_SPLUT, MuxVectorOperationThread)
OPERATIONTEST(vectorBoolX, S_BOOL, XVectorOperationThread)
OPERATIONTEST(vectorYaoX, S_YAO, XVectorOperationThread)
OPERATIONTEST(vectorBoolUniv, S_BOOL, UnivVectorOperationThread)
OPERATIONTEST(vectorYaoUniv, S_YAO, UnivVectorOperationThread)

OPERATIONCONVERTERTEST(VectorY2B, Y2BVectorOperationThread)
OPERATIONCONVERTERTEST(VectorB2A, B2AVectorOperationThread)
OPERATIONCONVERTERTEST(VectorB2Y, B2YVectorOperationThread)
OPERATIONCONVERTERTEST(VectorA2Y, A2YVectorOperationThread)
OPERATIONCONVERTERTEST(VectorA2B, A2BVectorOperationThread)
OPERATIONCONVERTERTEST(VectorY2A, Y2AVectorOperationThread)

OPERATIONTEST(standardBoolIO, S_BOOL, IOStandardOperationThread)
OPERATIONTEST(standardYaoIO, S_YAO, IOStandardOperationThread)
OPERATIONTEST(standardArithIO, S_ARITH, IOStandardOperationThread)
OPERATIONTEST(standardSplutIO, S_SPLUT, IOStandardOperationThread)
OPERATIONTEST(standardBoolAdd, S_BOOL, AddStandardOperationThread)
OPERATIONTEST(standardYaoAdd, S_YAO, AddStandardOperationThread)
OPERATIONTEST(standardArithAdd, S_ARITH, AddStandardOperationThread)
OPERATIONTEST(standardSPLUTAdd, S_SPLUT, AddStandardOperationThread)
OPERATIONTEST(standardBoolSub, S_BOOL, SubStandardOperationThread)
OPERATIONTEST(standardYaoSub, S_YAO, SubStandardOperationThread)
OPERATIONTEST(standardArithSub, S_ARITH, SubStandardOperationThread)
OPERATIONTEST(standardSplutSub, S_SPLUT, SubStandardOperationThread)
OPERATIONTEST(standardBoolMul, S_BOOL, MulStandardOperationThread)
OPERATIONTEST(standardYaoMul, S_YAO, MulStandardOperationThread)
OPERATIONTEST(standardArithMul, S_ARITH, MulStandardOperationThread)
OPERATIONTEST(standardSplutMul, S_SPLUT, MulStandardOperationThread)
OPERATIONTEST(standardBoolXor, S_BOOL, XorStandardOperationThread)
OPERATIONTEST(standardYaoXor, S_YAO, XorStandardOperationThread)
OPERATIONTEST(standardSplutXor, S_SPLUT, XorStandardOperationThread)
OPERATIONTEST(standardBoolAnd, S_BOOL, XorStandardOperationThread)
OPERATIONTEST(standardYaoAnd, S_YAO, AndStandardOperationThread)
OPERATIONTEST(standardSplutAnd, S_SPLUT, AndStandardOperationThread)
OPERATIONTEST(standardBoolCmp, S_BOOL, CmpStandardOperationThread)
OPERATIONTEST(standardYaoCmp, S_YAO, CmpStandardOperationThread)
OPERATIONTEST(standardSplutCmp, S_SPLUT, CmpStandardOperationThread)
OPERATIONTEST(standardBoolEq, S_BOOL, EqStandardOperationThread)
OPERATIONTEST(standardYaoEq, S_YAO, EqStandardOperationThread)
OPERATIONTEST(standardSplutEq, S_SPLUT, EqStandardOperationThread)
OPERATIONTEST(standardBooLMux, S_BOOL, MuxStandardOperationThread)
OPERATIONTEST(standardYaoMux, S_YAO, MuxStandardOperationThread)
OPERATIONTEST(standardSplutMux, S_SPLUT, MuxStandardOperationThread)
OPERATIONTEST(standardBoolX, S_BOOL, XStandardOperationThread)
OPERATIONTEST(standardYaoX, S_YAO, XStandardOperationThread)
OPERATIONTEST(standardBoolUniv, S_BOOL, UnivStandardOperationThread)
OPERATIONTEST(standardYaoUniv, S_YAO, UnivStandardOperationThread)

OPERATIONCONVERTERTEST(StandardY2B, Y2BStandardOperationThread)
OPERATIONCONVERTERTEST(StandardB2A, B2AStandardOperationThread)
OPERATIONCONVERTERTEST(StandardB2Y, B2YStandardOperationThread)
OPERATIONCONVERTERTEST(StandardA2Y, A2YStandardOperationThread)
OPERATIONCONVERTERTEST(StandardA2B, A2BStandardOperationThread)
OPERATIONCONVERTERTEST(StandardY2A, Y2AStandardOperationThread)

int main(int argc, char **argv) {
	testing::InitGoogleTest(&argc, argv);
	testing::AddGlobalTestEnvironment(ABYPartyTestParameters::GetABYPartyTestParameters());
	return RUN_ALL_TESTS();
}
